from django.contrib import admin
from django.urls import path, re_path, include

from horae import views

urlpatterns = (
    re_path(r'^$',views.noah_index),
    re_path(r'^index/$',views.noah_index),
    re_path(r'^(?P<pipe_id>\d+)/$', views.detail),
    re_path(r'^get_project_tree/$', views.get_project_tree),
    re_path(r'^search_pipeline/$', views.search_pipeline),
    re_path(r'^get_project_tree_async/$', views.get_project_tree_async),
    re_path(r'^get_pipeline_detail/$', views.get_pipeline_detail),
    re_path(r'^get_tasks/$', views.get_tasks),
    re_path(r'^unlink_task/$', views.unlink_task),
    re_path(r'^link_task/$', views.link_task),
    re_path(r'^update/(?P<pipe_id>\d+)/$', views.update),
    re_path(r'^copy_pipeline/$',views.copy_pipeline),
    re_path(r'^delete/(?P<pipe_id>\d+)/$', views.delete),
    re_path(r'^update_task/(?P<task_id>\d+)/$', views.update_task),
    re_path(r'^update_block/(?P<hash>.*)/$', views.update_block),
    re_path(r'^get_pipelines/$',views.get_pipelines),
    re_path(r'^get_server_tags/$', views.get_server_tags),
    re_path(r'^create_task/(?P<pipe_id>\d+)/$', views.create_task),
    re_path(r'^create/$', views.create),
    re_path(r'^get_user_list/$', views.get_user_list),
    re_path(r'^get_pipeline_with_project_tree/$', views.get_pipeline_with_project_tree),
    re_path(r'^history/$',views.history),
    re_path(r'^history_list/(?P<order_info>\w+)/$', views.history_list),
    re_path(r'^history/getlog/(?P<id>\d+)/$', views.get_task_information),
    re_path(r'^run_tasks/$', views.run_tasks),
    re_path(r'^history/(?P<pipe_id>\d+)/$', views.historypipe),
    re_path(r'^in_history/(?P<pipe_id>\d+)/$', views.in_historypipe),
    re_path(r'^get_params/$', views.get_params),
    re_path(r'^delete_task/(?P<pipe_id>\d+)/$', views.delete_task),
    re_path(r'^add_new_project/$', views.add_new_project),
    re_path(r'^get_message/$', views.get_message),
    re_path(r'^get_status_graph/$', views.get_status_graph),
    re_path(r'^get_graph/$', views.get_graph),
    re_path(r'^get_task_log/$', views.get_all_log_list),
    re_path(r'^get_log_content/$', views.get_log_content),
    re_path(r'^get_tail/$', views.get_tail),
    re_path(r'^download/(?P<args>.*)/$', views.big_file_download),
    re_path(r'^run_one_task/$', views.run_one_task),
    re_path(r'^run_one_pipeline/$', views.run_all_pipeline),
    re_path(r'^stop_task/$', views.stop_task),
    re_path(r'^run_task_with_all_successors/$', views.run_task_with_all_successors),
    re_path(r'^history/set_task_success/$', views.set_task_success),
    re_path(r'^run_some_task/$', views.run_some_task),
    re_path(r'^get_retry_history_list/$', views.get_retry_history_list),
    re_path(r'^on_line/$', views.on_line),
    re_path(r'^port_filter/$', views.port_filter),
    re_path(r'^futures_index/(?P<pipe_id>\d+)/$', views.futures_index),
    re_path(r'^futures_datas/$', views.futures_datas),
    re_path(r'^create_edge/$', views.create_edge),
    re_path(r'^update_edge/$', views.update_edge),
    re_path(r'^copy_task/$', views.copy_task),
    re_path(r'^copy_pipeline/$',views.copy_pipeline),
    re_path(r'^pindex/$',views.pindex),
    re_path(r'^liviz_index/$',views.liviz_index),
    re_path(r'^show_block/(?P<hash>.*)/$',views.show_block),
    re_path(r'^getDatas/$',views.get_datas),
)
