# Generated by Django 2.1 on 2018-08-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=16)),
                ('resource_id', models.BigIntegerField()),
                ('permission', models.CharField(max_length=200, verbose_name='seprated by |, like: read|update')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'denied'), (3, 'unsolicited grant'), (4, 'unsolicited revoke')], default=0)),
                ('deadline', models.DateTimeField(blank=True, default='2000-01-01 00:00:00', null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=512)),
                ('odps_perm_type', models.IntegerField(default=-1, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer_user', to=settings.AUTH_USER_MODEL)),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
