# Generated by Django 2.1 on 2018-08-20 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horae', '0002_permhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=128)),
                ('uri', models.CharField(max_length=128)),
                ('param', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=1024)),
                ('ip', models.CharField(default='', max_length=64)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_view_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
