# Generated by Django 2.1 on 2018-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0003_visitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
