# Generated by Django 2.1 on 2018-08-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0005_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='project_id',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
