# Generated by Django 2.1 on 2018-08-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0006_processor_project_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'type')},
        ),
    ]
