# Generated by Django 2.1 on 2018-08-29 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0008_auto_20180828_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='git_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='uploadhistory',
            unique_together={('processor_id', 'name')},
        ),
    ]
