# Generated by Django 2.1 on 2018-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0009_auto_20180829_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version_id',
            field=models.IntegerField(default=0),
        ),
    ]
