# Generated by Django 2.1 on 2018-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0010_task_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='version',
            field=models.CharField(max_length=250),
        ),
    ]
