# Generated by Django 2.1 on 2018-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0011_auto_20180907_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerunHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True, default=0)),
                ('run_time', models.CharField(db_index=True, max_length=20)),
                ('pl_id', models.IntegerField(db_index=True, default=0)),
                ('start_time', models.DateTimeField(default='2000-01-01 00:00:00', null=True, verbose_name='task start time')),
                ('end_time', models.DateTimeField(default='2000-01-01 00:00:00', null=True, verbose_name='task terminate time')),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('schedule_id', models.IntegerField(db_index=True, default=0)),
                ('tag', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(default=0)),
                ('task_handler', models.CharField(max_length=4096, null=True)),
                ('run_server', models.CharField(max_length=20, null=True)),
                ('server_tag', models.CharField(default='ALL', max_length=50)),
                ('pl_name', models.CharField(max_length=1024)),
                ('task_name', models.CharField(max_length=1024)),
            ],
        ),
    ]
