# Generated by Django 4.0 on 2022-02-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0013_auto_20180917_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_task_id', models.IntegerField(default=0)),
                ('next_task_id', models.IntegerField(default=0)),
                ('stream_type', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=1024, null=True)),
                ('rcm_context', models.CharField(default='', max_length=256, null=True)),
                ('rcm_topic', models.CharField(default='', max_length=256, null=True)),
                ('rcm_partition', models.IntegerField(default=0)),
                ('dispatch_tag', models.IntegerField(default=-1)),
                ('pipeline_id', models.IntegerField(default=0)),
                ('last_update_time_us', models.BigIntegerField(default=0, null=True)),
            ],
            options={
                'unique_together': {('prev_task_id', 'next_task_id')},
            },
        ),
    ]
