# Generated by Django 4.1 on 2024-09-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horae", "0014_edge"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.IntegerField(default=0)),
                ("email", models.CharField(default="", max_length=1024, null=True)),
                ("dingding", models.CharField(default="", max_length=256, null=True)),
            ],
        ),
    ]
