# Generated by Django 4.1 on 2024-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horae", "0015_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="readytask",
            name="ret_code",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="runhistory",
            name="ret_code",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="ret_code",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
