# Generated by Django 4.1 on 2024-09-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horae", "0016_readytask_ret_code_runhistory_ret_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhistory",
            name="type",
            field=models.IntegerField(default=-1),
        ),
    ]
